### ISSUE TITLE
`bootloader` on npm

### ISSUE THREAD

**Issue by PatrickJS** [GeorgeErickson/bootloader#1]
do you mind giving up `bootloader` on npm?

**Comment by PatrickJS** [comment]
@GeorgeErickson ping

**Comment by GeorgeErickson** [comment]
Sorry about the delay. Sure I can do that, I haven't used this in years.

**Comment by PatrickJS** [comment]
@GeorgeErickson thanks, I guess the best way is to add me to the npm module as an owner
username: gdi2290

**Comment by GeorgeErickson** [comment]
I think I added you (its been years since I've done js work), once it works I'll remove myself as an admin.

**Comment by PatrickJS** [comment]
@GeorgeErickson thanks! I got it
